package com.codemperor.ormcomparsion.dbflow

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.


import com.codemperor.ormcomparsion.dbflow.AppDatabase
import com.raizlabs.android.dbflow.annotation.Column
import com.raizlabs.android.dbflow.annotation.PrimaryKey
import com.raizlabs.android.dbflow.annotation.Table
import com.raizlabs.android.dbflow.structure.BaseModel

@Table(name = "NoteDBFlow", database = AppDatabase::class)
class NoteDBFlow : BaseModel {

    @PrimaryKey(autoincrement = true)
    @Column(name = "id")
    public var id: Long = 0


    @Column(name = "text")
    var text: String? = null
    @Column(name = "comment")
    var comment: String? = null
    @Column(name = "date")
    var date: java.util.Date? = null

    constructor() {}

    constructor(id: Long, text: String, comment: String, date: java.util.Date) {
        this.id = id
        this.text = text
        this.comment = comment
        this.date = date
    }

    override fun toString(): String {
        return "Note{" +
                "id=" + id +
                ", text='" + text + '\'' +
                ", comment='" + comment + '\'' +
                ", date=" + date +
                '}'
    }
}
